In [39]:
# Import Dependencies
import pandas as pd

In [40]:
# Reference the file where the CSV is located
crime_csv_path = "Resources/crime_incident_data2017.csv"

# Import the data into a Pandas DataFrame
crime_df = pd.read_csv(crime_csv_path)
crime_df

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
0,NaN,17-X4762181,Person,NaN,1,1/1/96,1/1/96,800,Sex Offenses,1,Rape,NaN,NaN,NaN,NaN,1/26/17,1/1/17
1,NaN,17-X4757824,Property,Centennial,1,1/20/00,1/1/00,1615,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/20/17,1/1/17
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
3,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/5/17,1/1/17
4,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Larceny Offenses,1,All Other Larceny,NaN,NaN,NaN,NaN,1/5/17,1/1/17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41027,8800 BLOCK OF NE SANDY BLVD,17-285386,Society,Sumner,1,8/31/17,8/1/17,535,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5554,-122.571,7671560.0,695399.0,8/31/17,8/1/17
41028,9700 BLOCK OF SE STARK ST,17-286082,Society,Hazelwood,1,8/31/17,8/1/17,1619,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41029,9700 BLOCK OF SE STARK ST,17-286413,Society,Hazelwood,1,8/31/17,8/1/17,1959,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41030,UNKNOWN ADDRESS,17-286445,Society,NaN,1,8/31/17,8/1/17,2021,Prostitution Offenses,1,Prostitution,NaN,NaN,NaN,NaN,8/31/17,8/1/17
41031,8000 BLOCK OF SE POWELL BLVD,17-286659,Society,Foster-Powell,1,8/31/17,8/1/17,2354,Weapon Law Violations,1,Weapons Law Violations,45.4974,-122.580,7668725.0,674298.0,8/31/17,8/1/17

In [41]:
# look for missing values
crime_df.count()

Address              37365
Case Number          41032
Crime Against        41032
Neighborhood         39712
Number of Records    41032
Occur Date           41032
Occur Month Year     41032
Occur Time           41032
Offense Category     41032
Offense Count        41032
Offense Type         41032
Open Data Lat        36712
Open Data Lon        36712
Open Data X          36712
Open Data Y          36712
Report Date          41032
Report Month Year    41032
dtype: int64

In [42]:
crime_df['Category and Type'] = crime_df['Offense Category'] + ' / ' + crime_df['Offense Type']
crime_df

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year,Category and Type
0,NaN,17-X4762181,Person,NaN,1,1/1/96,1/1/96,800,Sex Offenses,1,Rape,NaN,NaN,NaN,NaN,1/26/17,1/1/17,Sex Offenses / Rape
1,NaN,17-X4757824,Property,Centennial,1,1/20/00,1/1/00,1615,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/20/17,1/1/17,Fraud Offenses / Identity Theft
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17,Fraud Offenses / False Pretenses/Swindle/Confi...
3,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/5/17,1/1/17,Fraud Offenses / Identity Theft
4,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Larceny Offenses,1,All Other Larceny,NaN,NaN,NaN,NaN,1/5/17,1/1/17,Larceny Offenses / All Other Larceny
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41027,8800 BLOCK OF NE SANDY BLVD,17-285386,Society,Sumner,1,8/31/17,8/1/17,535,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5554,-122.571,7671560.0,695399.0,8/31/17,8/1/17,Drug/Narcotic Offenses / Drug/Narcotic Violations
41028,9700 BLOCK OF SE STARK ST,17-286082,Society,Hazelwood,1,8/31/17,8/1/17,1619,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17,Prostitution Offenses / Prostitution
41029,9700 BLOCK OF SE STARK ST,17-286413,Society,Hazelwood,1,8/31/17,8/1/17,1959,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17,Prostitution Offenses / Prostitution
41030,UNKNOWN ADDRESS,17-286445,Society,NaN,1,8/31/17,8/1/17,2021,Prostitution Offenses,1,Prostitution,NaN,NaN,NaN,NaN,8/31/17,8/1/17,Prostitution Offenses / Prostitution
41031,8000 BLOCK OF SE POWELL BLVD,17-286659,Society,Foster-Powell,1,8/31/17,8/1/17,2354,Weapon Law Violations,1,Weapons Law Violations,45.4974,-122.580,7668725.0,674298.0,8/31/17,8/1/17,Weapon Law Violations / Weapons Law Violations

In [43]:
# drop null rows
no_null_crime_df = crime_df.dropna(how='all')

In [44]:
# verify counts
no_null_crime_df.count()

Address              37365
Case Number          41032
Crime Against        41032
Neighborhood         39712
Number of Records    41032
Occur Date           41032
Occur Month Year     41032
Occur Time           41032
Offense Category     41032
Offense Count        41032
Offense Type         41032
Open Data Lat        36712
Open Data Lon        36712
Open Data X          36712
Open Data Y          36712
Report Date          41032
Report Month Year    41032
Category and Type    41032
dtype: int64

In [45]:
# Check to see if there are any values with mispelled or similar values in "Offense Type"
no_null_crime_df["Offense Type"].value_counts()

Theft From Motor Vehicle                       7256
All Other Larceny                              4900
Motor Vehicle Theft                            4799
Vandalism                                      4189
Burglary                                       2901
Simple Assault                                 2453
Shoplifting                                    2332
Identity Theft                                 2040
Intimidation                                   1678
Aggravated Assault                             1217
Drug/Narcotic Violations                       1142
Theft of Motor Vehicle Parts or Accessories    1107
False Pretenses/Swindle/Confidence Game         972
Theft From Building                             961
Robbery                                         680
Counterfeiting/Forgery                          470
Weapons Law Violations                          298
Credit Card/ATM Fraud                           264
Rape                                            228
Arson                                           221
Prostitution                                    166
Fondling                                        147
Pocket-Picking                                  107
Purse-Snatching                                  98
Embezzlement                                     78
Stolen Property Offenses                         59
Kidnapping/Abduction                             56
Sodomy                                           51
Hacking/Computer Invasion                        22
Theft From Coin-Operated Machine or Device       20
Animal Cruelty                                   19
Statutory Rape                                   18
Murder and Non-negligent Manslaughter            14
Extortion/Blackmail                              13
Pornography/Obscene Material                     11
Assisting or Promoting Prostitution              11
Sexual Assault With An Object                    10
Impersonation                                     6
Drug Equipment Violations                         6
Wire Fraud                                        4
Involuntary Servitude                             4
Commercial Sex Acts                               2
Incest                                            1
Welfare Fraud                                     1
Name: Offense Type, dtype: int64

In [46]:
# Combining similar offenses together
no_null_crime_df = no_null_crime_df.replace(
    {"Commercial Sex Acts": "Prostitution", "Assisting or Promoting Prostitution": "Prostitution"})
no_null_crime_df

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year,Category and Type
0,NaN,17-X4762181,Person,NaN,1,1/1/96,1/1/96,800,Sex Offenses,1,Rape,NaN,NaN,NaN,NaN,1/26/17,1/1/17,Sex Offenses / Rape
1,NaN,17-X4757824,Property,Centennial,1,1/20/00,1/1/00,1615,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/20/17,1/1/17,Fraud Offenses / Identity Theft
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17,Fraud Offenses / False Pretenses/Swindle/Confi...
3,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/5/17,1/1/17,Fraud Offenses / Identity Theft
4,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Larceny Offenses,1,All Other Larceny,NaN,NaN,NaN,NaN,1/5/17,1/1/17,Larceny Offenses / All Other Larceny
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41027,8800 BLOCK OF NE SANDY BLVD,17-285386,Society,Sumner,1,8/31/17,8/1/17,535,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5554,-122.571,7671560.0,695399.0,8/31/17,8/1/17,Drug/Narcotic Offenses / Drug/Narcotic Violations
41028,9700 BLOCK OF SE STARK ST,17-286082,Society,Hazelwood,1,8/31/17,8/1/17,1619,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17,Prostitution Offenses / Prostitution
41029,9700 BLOCK OF SE STARK ST,17-286413,Society,Hazelwood,1,8/31/17,8/1/17,1959,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17,Prostitution Offenses / Prostitution
41030,UNKNOWN ADDRESS,17-286445,Society,NaN,1,8/31/17,8/1/17,2021,Prostitution Offenses,1,Prostitution,NaN,NaN,NaN,NaN,8/31/17,8/1/17,Prostitution Offenses / Prostitution
41031,8000 BLOCK OF SE POWELL BLVD,17-286659,Society,Foster-Powell,1,8/31/17,8/1/17,2354,Weapon Law Violations,1,Weapons Law Violations,45.4974,-122.580,7668725.0,674298.0,8/31/17,8/1/17,Weapon Law Violations / Weapons Law Violations

In [47]:
# Check to see if you combined similar offenses correctly in "Offense Type".
no_null_crime_df["Offense Type"].value_counts()

Theft From Motor Vehicle                       7256
All Other Larceny                              4900
Motor Vehicle Theft                            4799
Vandalism                                      4189
Burglary                                       2901
Simple Assault                                 2453
Shoplifting                                    2332
Identity Theft                                 2040
Intimidation                                   1678
Aggravated Assault                             1217
Drug/Narcotic Violations                       1142
Theft of Motor Vehicle Parts or Accessories    1107
False Pretenses/Swindle/Confidence Game         972
Theft From Building                             961
Robbery                                         680
Counterfeiting/Forgery                          470
Weapons Law Violations                          298
Credit Card/ATM Fraud                           264
Rape                                            228
Arson                                           221
Prostitution                                    179
Fondling                                        147
Pocket-Picking                                  107
Purse-Snatching                                  98
Embezzlement                                     78
Stolen Property Offenses                         59
Kidnapping/Abduction                             56
Sodomy                                           51
Hacking/Computer Invasion                        22
Theft From Coin-Operated Machine or Device       20
Animal Cruelty                                   19
Statutory Rape                                   18
Murder and Non-negligent Manslaughter            14
Extortion/Blackmail                              13
Pornography/Obscene Material                     11
Sexual Assault With An Object                    10
Impersonation                                     6
Drug Equipment Violations                         6
Wire Fraud                                        4
Involuntary Servitude                             4
Incest                                            1
Welfare Fraud                                     1
Name: Offense Type, dtype: int64

In [48]:
# Create a new DataFrame that looks into a specific neighborhood
vernon_crime_df = crime_df.loc[no_null_crime_df["Neighborhood"] == "Vernon"]
vernon_crime_df

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year,Category and Type
6,5000 BLOCK OF NE 19TH AVE,17-901079,Property,Vernon,1,11/8/13,11/1/13,1200,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5594,-122.646,7652567.0,697337.0,1/26/17,1/1/17,Fraud Offenses / False Pretenses/Swindle/Confi...
7,5000 BLOCK OF NE 19TH AVE,17-901079,Property,Vernon,1,11/8/13,11/1/13,1200,Fraud Offenses,1,Identity Theft,45.5594,-122.646,7652567.0,697337.0,1/26/17,1/1/17,Fraud Offenses / Identity Theft
147,1000 BLOCK OF NE EMERSON ST,17-901190,Property,Vernon,1,11/26/16,11/1/16,2040,Fraud Offenses,1,Identity Theft,45.5619,-122.655,7650320.0,698297.0,1/29/17,1/1/17,Fraud Offenses / Identity Theft
148,1000 BLOCK OF NE EMERSON ST,17-901190,Property,Vernon,1,11/26/16,11/1/16,2040,Larceny Offenses,1,All Other Larceny,45.5619,-122.655,7650320.0,698297.0,1/29/17,1/1/17,Larceny Offenses / All Other Larceny
271,5300 BLOCK OF NE 14TH PL,17-2593,Property,Vernon,1,12/19/16,12/1/16,900,Larceny Offenses,1,All Other Larceny,45.5618,-122.651,7651314.0,698264.0,1/3/17,1/1/17,Larceny Offenses / All Other Larceny
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39759,NE 21ST AVE / NE ALBERTA ST,17-276989,Property,Vernon,1,8/24/17,8/1/17,1500,Larceny Offenses,1,Purse-Snatching,45.5591,-122.644,7653047.0,697209.0,8/24/17,8/1/17,Larceny Offenses / Purse-Snatching
39875,4800 BLOCK OF NE 14TH PL,17-912435,Property,Vernon,1,8/24/17,8/1/17,0,Larceny Offenses,1,Theft From Motor Vehicle,45.5581,-122.651,7651302.0,696885.0,8/25/17,8/1/17,Larceny Offenses / Theft From Motor Vehicle
40920,1800 BLOCK OF NE JARRETT ST,17-285898,Property,Vernon,1,8/30/17,8/1/17,2130,Motor Vehicle Theft,1,Motor Vehicle Theft,45.5646,-122.647,7652420.0,699227.0,8/31/17,8/1/17,Motor Vehicle Theft / Motor Vehicle Theft
40942,NaN,17-X4925990,Person,Vernon,1,8/31/17,8/1/17,649,Assault Offenses,1,Intimidation,NaN,NaN,NaN,NaN,8/31/17,8/1/17,Assault Offenses / Intimidation
40951,NaN,17-X4919573,Person,Vernon,1,8/31/17,8/1/17,258,Assault Offenses,1,Simple Assault,NaN,NaN,NaN,NaN,8/31/17,8/1/17,Assault Offenses / Simple Assault